<a href="https://colab.research.google.com/github/shuken1019/Python25study/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#넘파이 ndarray 개요
import numpy as np
array1=np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape) #array 차원과 크기를 튜플 형태로 나타내줌
#[1,2,3]인 array1의 shape는 (3,)입니다.
#1차원 array로 3개의 데이터를 가지고 있다.

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [8]:
array2=np.array([[1,2,3],[2,3,4]])#array2 의 shape는 (2,3)입니다.
# 2차원 array로 2개의 로우와 3개의 칼럼으로구성되어 2*3=6개의 데이터를 가지고 있다.
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [9]:
array3=np.array([[1,2,3]])
print('array3 type:',type((array3)))
print('array3 array형태:',array3.shape)
#1개의 로우와 3개의 칼럼으로 구성된 2차원 데이터를 의미한다.
#array3는 array1과 동일한 데이터 건수를 가지고 있지만, array1은 명확하게 1차원임을 (3,)표현한 것이며,
#array3 역시 명확하게 로우와 칼럼으로 이뤄진 2차원 데이터임을 (1,3)으로 표현한것이다.

array3 type: <class 'numpy.ndarray'>
array3 array형태: (1, 3)


In [11]:
print('array1:{0}차원,array2:{1}차원,array3:{2}차원'.format(array1.ndim,array2.ndim,array3.ndim))
#array1은 1차원 array3은 2차원 임을 할 수 잇다.
#array ()함수의 인자로는 파이선의 리스트 객체가 주로 사용됨
#리스트[] 은 1차원이고, 리스트의 리스트[[]] 2차원의 같은 형태로 배열의 차원과 크기를 쉽게 표현할 수 잇기 대문이다.


array1:1차원,array2:2차원,array3:2차원


In [12]:
#ndarray의 데이터 타입
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [13]:
list2 =[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype)

#int형값과 문자열이 섞여있는 list2를 변환한 1,2가 모두 문자열 값인 '1','2'로 변환됨
#데이터 값이 모두 같은데이터 타입이어야 하므로 서로다른 데이터 타입이 섞여 있을 경우 데이터 타입이 더 큰 데이터 타입으로 변환
#int형이 유니코드 문자열 값으로 변환됨.

['1' '2' 'test'] <U21


In [14]:
list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)
#int와 float형이 섞여있는 list3의 경우도 int1,2가 모두 1.2.dls float64형으로 변환됨

[1. 2. 3.] float64


In [15]:
#ndarray 내 데이터값의 타입 변경도 astype 메서드를 이용해 할 수 있음.
#데이터 타입을 변경하는 경우는 대용량 데이터의 ndarray를 만들 때 많은 메모리가 사용되는데, 메모리를 더 절약할 때 보통 이용됨.
#파이썬기반의 머신러닝 알고리즘은 대부분 메모리로 데이터를 전체 로딩한 다음 이를 기반으로 알고리즘 적용하기 때문에
#대용량의 데이터를 로딩할 때는 수행속도가 느려지거나 메모리 부족으로 오류가 발생할 수 있음.

array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)
#int32형 데이터를 float64로 변환함

[1. 2. 3.] float64


In [16]:
array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)
#float64를 다시 int32형으로 변환함

[1 2 3] int32


In [17]:
array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)
#float를 int형으로 변경할 경우에는 소수점 이하는 당연히 없어짐

[1 2 3] int32
